version: "3.8"

services:
  postgres:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_DB=demoday
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/backup:/backup
    ports:
      - "5432:5432"
    container_name: demoday_postgres
